title: Sai Teja Reddy
theme: jekyll-theme-minimal
logo: assets/Image.jpeg

description: |
  Data Analyst • Analytics • Data Engineering<br>
  <a href="mailto:chsaitejareddy2002@gmail.com">Email</a> •
  <a href="https://github.com/saitejareddy1220">GitHub</a> •
  <a href="https://www.linkedin.com/in/sai-teja-reddy-ch/">LinkedIn</a>
