title: Sai Teja Reddy
theme: jekyll-theme-minimal
logo: Image.jpeg

description: |
  Data Analyst • Analytics • Data Engineering<br>
  Email: <a href="mailto:chsaitejareddy2002@gmail.com">chsaitejareddy2002@gmail.com</a><br>
  GitHub: <a href="https://github.com/saitejareddy1220">saitejareddy1220</a><br>
  LinkedIn: <a href="https://www.linkedin.com/in/sai-teja-reddy-ch/">sai-teja-reddy-ch</a>
