title: Sai Teja Reddy
logo: Image.jpeg
**Data Analyst** \| **Analytics** \| **Data Engineering**
ğŸ“§ Email: chsaitejareddy2002@gmail.com
ğŸ”— LinkedIn: https://www.linkedin.com/in/sai-teja-reddy-ch/
ğŸ’» GitHub: https://github.com/saitejareddy1220
theme: jekyll-theme-minimal
