title: Sai Teja Reddy
logo: Image.jpeg

description: |
  Data Analyst • Analytics • Data Engineering  
  **Email:** [chsaitejareddy2002@gmail.com](mailto:chsaitejareddy2002@gmail.com)  
  **GitHub:** [saitejareddy1220](https://github.com/saitejareddy1220)  
  **LinkedIn:** [sai-teja-reddy-ch](https://www.linkedin.com/in/sai-teja-reddy-ch/)
theme: jekyll-theme-minimal
